name: Keep Website Alive

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes

jobs:
  ping-website:
    runs-on: ubuntu-latest
    steps:
      - name: Ping PaperTradeX website
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -L https://papertardex.streamlit.app)
          echo "HTTP Status Code: $STATUS_CODE"
          if [[ "$STATUS_CODE" != "200" ]]; then
            echo "Warning: Website returned status $STATUS_CODE"
            exit 1
          fi
