name: Keep Streamlit App Alive

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # allows manual trigger

jobs:
  ping-site:
    runs-on: ubuntu-latest

    steps:
      - name: Ping the Streamlit app
        run: |
          curl -I https://papertardex.streamlit.app || exit 1
